package uz.market.entity.enums;

public enum State {
    AUTHORIZATION,
    PHONE_NUMBER_REQUEST,
    SELLER_MAIN, BUYER_MAIN,
    CREATE_SHOP,
    BUYER_SELECTING_SHOP,
    BUYER_SELECTING_PRODUCT,
    BUYER_MANAGING_BALANCE
}
